"""Add schema caching fields to database_connection

Revision ID: 1801c9c93e30
Revises: fab3c0f10a15
Create Date: 2026-02-13 02:03:54.217638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1801c9c93e30'
down_revision = 'fab3c0f10a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database_connections', sa.Column('schema_json_path', sa.String(), nullable=True))
    op.add_column('database_connections', sa.Column('schema_generated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('database_connections', 'schema_generated_at')
    op.drop_column('database_connections', 'schema_json_path')
    # ### end Alembic commands ###
