"""add_ssl_fields_to_database_connections

Revision ID: 31531587d8a6
Revises: bf74f3bc4393
Create Date: 2026-02-14 14:21:01.917109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31531587d8a6'
down_revision = 'bf74f3bc4393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database_connections', sa.Column('ssl_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('database_connections', sa.Column('ssl_ca_cert', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('database_connections', 'ssl_ca_cert')
    op.drop_column('database_connections', 'ssl_enabled')
    # ### end Alembic commands ###
