"""Add model column to token_usage

Revision ID: bf74f3bc4393
Revises: 1801c9c93e30
Create Date: 2026-02-13 15:43:46.153199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf74f3bc4393'
down_revision = '1801c9c93e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_usage', sa.Column('model', sa.String(), nullable=False, server_default='unknown'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_usage', 'model')
    # ### end Alembic commands ###
